[package]
name = "libstrings"
version = "0.1.0"
authors = ["Daniel Schuele <daniel.schuele@bruker.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
